### ISSUE TITLE
Loosen requirement versions

### ISSUE THREAD

**Issue by impredicative** [Broundal/Pytolemaic#3]
When using `setup.py`, it is definitely not appropriate to tightly pin requirement versions. They must then be loosely pinned if at all. Please review https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires

> it’s best practice to indicate any known lower or upper bounds

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

I advise updating `requirements.txt` to loosely pin its entries as advised in the above article. I see that `requirements.txt` is used by `install_requires` in `setup.py`.

**Comment by Broundal** [comment]
Thanks! Appreciated!
