### ISSUE TITLE
Logging Issue

### ISSUE THREAD

**Issue by watson-sam** [Broundal/Pytolemaic#6]
Hi,

The logger in https://github.com/Broundal/Pytolemaic/blob/master/pytolemaic/utils/general.py is causing issues; it really should be up to the user what and how the logging is done etc, I know could use a LOGLEVEL env var but thats not really how these things work; the logger should be created in the .py file that actually runs the code and not a package that provides functionality. 

Big fan aside from this but please amend as makes this whole unusable for me otherwise!

**Comment by Broundal** [comment]
Hi @watson-sam,
Thank you for your warm words and the feedback!
Logging was indeed something I overlooked. I have changed the logging to use loggers instead of logging's root logger. Please let me know if this modification fixes your issue.

**Comment by watson-sam** [comment]
Looks to be all sorted - thanks for the quick response and change - tah!
